#Path to arduino sources
ARDUINO_DIR = /usr/share/arduino

#Path to arduino device
ARDUINO_PORT = /dev/ttyUSB0

#Currnet directory path
CURRENT_DIR = $(shell pwd)

#Path to the users libreries
USER_LIB_PATH = ${CURRENT_DIR}/libraries

#Arduinno Model
BOARD_TAG = uno

#Includes Arduino make file for building and flashing the scketch
include ${ARDUINO_DIR}/Arduino.mk
